### ISSUE TITLE
add custom timeouts for hard deposits

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/swap-swear-and-swindle#10]
Currently hard deposits can be decreased to 0 after 2 days which breaks all attempts at offchain swear.

**Comment by Eknir** [comment]
How do you envision this? Having a different timeout per beneficiary? Having a different timeout per SWAP contract? In what way does the current implementation break attempts at offchain swear?

**Comment by ralph-pichler** [comment]
It breaks everything that needs hard guarantees on the contract remaining liquid for more than the hard coded time period (as the owner can always completely empty the contract within hardDepositTimeout seconds). 

Ideally we can set the decrease timeout on a per beneficiary basis with a default timeout if not set. Instant decrease should still be possible, but only with the beneficiaries approval (e.g. with some signed data or a function that can be called by the beneficiary).

**Comment by Eknir** [comment]
Started working
