### ISSUE TITLE
Use go modules for the go-sw3 library

### ISSUE THREAD

**Issue by paxthemax** [ethersphere/swap-swear-and-swindle#113]
# Description

Currently the build/CI process automatically creates a separate folder for a new version of the S/S/S contracts.

Use a go module with a **major** version update for a more idiomatic way to reference the generated code.

**Comment by Eknir** [comment]
Hi @paxthemax , what do we do with this PR? Let's clean up: merge or close. Thanks!

**Comment by paxthemax** [comment]
I would consider closing this, and reopening in the proper repository.
