### ISSUE TITLE
Wrong factory and token contract

### ISSUE THREAD

**Issue by r0qs** [ethersphere/swap-swear-and-swindle#119]
Hi, in the [documentation](https://github.com/ethersphere/swap-swear-and-swindle#test-deployments) this address: [0xA6B88705036F2a56807af157c116b7dfCDabf968](https://goerli.etherscan.io/address/0xA6B88705036F2a56807af157c116b7dfCDabf968) is said to be the default factory using this token address: [0xe1927106821DB21c8657B8EB483705E95903eE93](https://goerli.etherscan.io/address/0xe1927106821db21c8657b8eb483705e95903ee93)

But the bee clients are currently setting this address: [0xf0277CAFfea72734853B834AFC9892461eA18474](https://goerli.etherscan.io/address/0xf0277CAFfea72734853B834AFC9892461eA18474) as the default factory contract and this address [0x2aC3c1d3e24b45c6C310534Bc2Dd84B5ed576335](https://goerli.etherscan.io/address/0x2aC3c1d3e24b45c6C310534Bc2Dd84B5ed576335) as the token contract.

Here is the bee code that set the factory: https://github.com/ethersphere/bee/blob/master/pkg/settlement/swap/chequebook/factory.go#L172

Which one is the correct? If is the latter, could you also validate the contract code in etherscan? https://goerli.etherscan.io/address/0x2ac3c1d3e24b45c6c310534bc2dd84b5ed576335#code

**Comment by r0qs** [comment]
I just noticed that there is actually a PR https://github.com/ethersphere/swap-swear-and-swindle/pull/118 to fix the issue. It would be great to merge it in the master. And also do the verification of the token contract in etherscan :)

**Comment by ralph-pichler** [comment]
yeah, seems I forgot to hit the merge button on that one. should be fixed now.
