### ISSUE TITLE
clean up the commitment related code

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/swap-swear-and-swindle#18]
offchain and onchain use the same fields differently
not every field might be necessary

**Comment by ralph-pichler** [comment]
offchain and onchain Swear have been separated. cleanup is still necessary regarding open cases logic.

**Comment by Eknir** [comment]
Still relevant @ralph-pichler?

**Comment by ralph-pichler** [comment]
No, this was for the previous design. The new contracts don't have commitments anymore.
