### ISSUE TITLE
drop submitCheque and make sure this is safe for the owner

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swap-swear-and-swindle#25]
submitChequeLower supposedly can do everything which submitCheque can do as well. For code clarity, we can drop submitCheque and rename submitChequeLower to submitCheque.

We have to gather sufficient reasoning on the safety of dropping this function (no party should be able to game the other party), as well as a gas-cost analysis.

**Comment by vojtechsimetka** [comment]
@Eknir will work on this

**Comment by Eknir** [comment]
Pull request created, waiting for review https://github.com/ethersphere/swap-swear-and-swindle/pull/38
