### ISSUE TITLE
Get rid of custom .encode functions where possible

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swap-swear-and-swindle#27]

**Comment by ralph-pichler** [comment]
The .encode* functions are only necessary because they are used in the JS testing. If all encoding ist done JS side they don't have to be in the contract.

For SimpleSwap this is only encodeNote (which isn't even needed there, could be moved to Swap).

**Comment by Eknir** [comment]
We should delete these .encode functions in production, as it will decrease the size of the to-be-deployed smart-contracts.

**Comment by ralph-pichler** [comment]
With the SW3Utils inheritance removed from SimpleSwap this now no longer affects SimpleSwap.

**Comment by ralph-pichler** [comment]
I'm closing this since this no longer affects any contracts which are on master.
