### ISSUE TITLE
eth_signTypedData or other signing mechanism 

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swap-swear-and-swindle#28]
Related EIP: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md

**Comment by ralph-pichler** [comment]
For now we are using the standard eth_sign mechanism which adds the "Ethereum Signed Message" prefix. Since we will sign cheques directly from the go code and not through the web3 api we could also sign the message directly. Either way is possible (or we could use eth_signTypedData).

**Comment by ralph-pichler** [comment]
We implemented support for the `eth_sign` way on the go side for now. We still should probably revisit this at some point.
