### ISSUE TITLE
Design deployment and deploy smart contracts

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swap-swear-and-swindle#31]
Design how the smart contracts need to be deployed (which testnet, configuration needed, etc.).

Setup / share tools for deployment and document.

Deploy to testnet.

**Comment by Eknir** [comment]
smart-contract should be deployed by the go code. 
We have to check whether the v2 encode is supported.

**Comment by ralph-pichler** [comment]
Related to ethersphere/swarm#1583.

**Comment by paxthemax** [comment]
Related to #113

**Comment by Eknir** [comment]
This can be closed
