### ISSUE TITLE
_computePayout

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swap-swear-and-swindle#32]
The _computePayout function could be structured more simply.

**Comment by vojtechsimetka** [comment]
@holisticode can you add this to the current sprint in https://github.com/orgs/ethersphere/projects/9 ? @Eknir will work on this.

**Comment by Eknir** [comment]
Work done. Need approval for pull request. See: https://github.com/ethersphere/swap-swear-and-swindle/pull/41

**Comment by Eknir** [comment]
merged in masater
