### ISSUE TITLE
ERC20 integration

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swap-swear-and-swindle#35]
1. Make chequebook ERC20-compatible
2. Adapt ABIGEN script / CI script en push go-bindings to a different repo
3. Make Swarm source-code work with ERC20 compatible go-bindings

**Comment by Eknir** [comment]
The chequebookFactory must also be updated. Proposal to create two versions `SimpleSwap.sol`, initialize the cheqeubook with a `tokenAddress`. If the `tokenAddress` of the factory is `0x00...`, deploy the `SimpleSwap.sol` with the native token, if `tokenAddress` of the factory is set, deploy `ERC20SimpleSwap.sol` with the ERC20-contract living at `tokenAddress`

**Comment by ralph-pichler** [comment]
Smart contract side is finished. Work on go is going on in https://github.com/ethersphere/swarm/pull/1964.
