### ISSUE TITLE
Parameter orders in cheqeuHash function / keccak256 hash in body of function

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swap-swear-and-swindle#36]
Order of parameters in function cheqeuHash does not match the order of these parameters in the keccak256 hash. 
Proposal: change the order of parameters in the function or change the order of parameters in the keccak256 hash in the body of this function.

```  function chequeHash(address swap, address beneficiary, uint serial, uint amount, uint timeout)
  public pure returns (bytes32) {
    return keccak256(abi.encodePacked(swap, serial, beneficiary, amount, timeout));
  }```

**Comment by ralph-pichler** [comment]
This was fixed in #68
