### ISSUE TITLE
Using the newest version of openZeppelin solidity

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swap-swear-and-swindle#37]
Upgrading to the newest version of openzeppelin Solidity breaks the smart-contract when deployed on Ganache.
Reason: Ganache does not inject the correct value for v. (0 or 1, instead of 27 or 28).

Current solution in place: Use openzepplinSolidity version: 2.1.2
Desired solution: make the repository compatible with the newest version of openzeppelin solidity.

**Comment by ralph-pichler** [comment]
Updated in #55
