### ISSUE TITLE
Swear contract design

### ISSUE THREAD

**Issue by VoR0220** [ethersphere/swap-swear-and-swindle#4]
Problem: The current SWEAR design seems like it could be simplified. When I was reading through the orange papers, I came up with a design for a SWEAR deposit system (the name may be incorrect) that could look like this. With this design you can keep deposits moving through indefinitely and attach other modules that rely on information regarding deposits to different nodes. Keep in mind this is just an abstract sketch.

```
pragma solidity >= 0.4.13;

contract SWEAR {
    
    uint swarmEpoch = 3 days;
    
    mapping(address=>Deposit) public deposits;
    
    struct Deposit {
        bool inDepositPeriod;
        uint vestingPeriod;
        uint depositedAmount;
    }
    
    function() {
        revert();
    }
    
    function register(uint epochs) payable returns (bool) {
        if (!deposits[msg.sender].inDepositPeriod) {
            deposits[msg.sender] = Deposit({inDepositPeriod: true, vestingPeriod: now + epochs * swarmEpoch, depositedAmount: msg.value});
            return true;
        }
        if (msg.value > 0) { revert(); }
        // can't reregister, return false telling node that it cannot alter its deposit
        return false;
    }
    
    function collectDeposit() external returns (bool) {
        Deposit storage depositInfo = deposits[msg.sender];
        if (depositInfo.inDepositPeriod && depositInfo.vestingPeriod <= now) {
            uint toTransfer = depositInfo.depositedAmount;
            deposits[msg.sender] = Deposit(false, 0, 0);
            msg.sender.transfer(toTransfer);
            return true;
        }
        return false;
    }
}
```

**Comment by zelig** [comment]
@VoR0220 yes great, something like this is good. We gotta make it a witness and then
we could have a generic swindle and use this for checking service provider validity

**Comment by orenyodfat** [comment]
@zelig we can make it a witness which testify for services and clients deposits as a pre trial condition.
This witness should be called to testify upon each client (player) registration so the contract can assure that there is enough deposit for the case of a compensation for a valid case.

The term "witness" is a bit misleading here..what about call it "registrar" ?

**Comment by Eknir** [comment]
Can this issue be closed?

**Comment by ralph-pichler** [comment]
Can be closed. This was a very old version of Swear.
